### ISSUE TITLE
Posizione "Portfolio"

### ISSUE THREAD

**Issue by Pietrofontaz** [Pietrofontaz/pietrofontaz.github.io#1]
@grammaton Parola portfolio che non risponde ai caratteri di Atom (dimensione diversa) e non si riesce a posizionare più centrato.

**Comment by grammaton** [comment]
ho fatto la classe `portfolio` dentro `main.css`. fammi sapere come va.
per vedere le modifiche devi fare merge alla pull request #2

**Comment by Pietrofontaz** [comment]
Purtroppo non riesco a modificare il testo, lo vorrei un po' più piccolo ma nonostante io faccia modifiche lui non sembra essere d'accordo.

**Comment by Pietrofontaz** [comment]
Scherzavo, problema risolto!

**Comment by Pietrofontaz** [comment]
Sono riuscito a sistemare tutto con Portfolio, grazie mille! Ora le ho
mandato un altro Issue, ma in realtà solo la prima parte delle 2 è quella
che mi interessa davvero,  la seconda solo se rimane tempo. Grazie mille
ancora.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno dom 23 giu 2019 alle ore 14:15 Giuseppe <notifications@github.com>
ha scritto:

**Comment by Pietrofontaz** [comment]
Come non detto, oggi ho acceso tutto di nuovo ed era così. Il sito si è
sfasciato totalmente.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno mar 25 giu 2019 alle ore 09:43 Pietro Fontanesi <
pietrofontaz@gmail.com> ha scritto:

**Comment by Pietrofontaz** [comment]
Ho fatto confusione con le mail. Allora, ho unito le branches e sistemato
un po' il carattere, ieri sera ho salvato e funzionava, stamattina è tutto
sfasciato, ma solo su jekyll serve, (allego immagine), perchè in realtà il
sito funziona perfettamente. Spiegazioni? (Così per sistemare cose devo per
forza caricare tutti gli update e non guardare solo in locale, che era
estremamente più comodo. In più ho aggiunto un paio di cose su Issues,
spero faccia in tempo ad aiutarmi.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno dom 23 giu 2019 alle ore 14:15 Giuseppe <notifications@github.com>
ha scritto:
